name: weather_stacked
description: An app build with the stacked framework
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  geolocator: ^9.0.2
  dio: ^5.2.0+1
  flex_color_scheme: ^7.1.2
  retrofit: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.5
  stacked_generator: ^1.3.3
  mockito: ^5.4.1
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.1

flutter:
  uses-material-design: true
